# -*- coding: utf-8 -*-
"""
/***************************************************************************
 gas_data_import
                                 A QGIS plugin
 This plugin allows for the direct import and formatting of gas data from the text file output of the Laser Methan Mini data logger.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-01
        copyright            : (C) 2019 by Silver Spring Energy Consulting Ltd.
        email                : tpubben@silverspringenergy.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load gas_data_import class from file gas_data_import.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lmm_gas_import import gas_data_import
    return gas_data_import(iface)
